CREATE TABLE roles (
  id      BIGSERIAL PRIMARY KEY,
  name    VARCHAR(40),
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_role (
  id BIGSERIAL,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL DEFAULT 2,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TRIGGER set_updated_at_user_role BEFORE UPDATE ON roles FOR EACH ROW EXECUTE PROCEDURE trigger_set_update_at();
CREATE TRIGGER set_updated_at_user BEFORE UPDATE ON user_role FOR EACH ROW EXECUTE PROCEDURE trigger_set_update_at();